---
title: "Midterm Group Project"
output: html_notebook
---



# JOINING ALL DATA
# changes <2.5 to 2.5

final_data <- inner_join(fao_data_set,covid19, by = "Area") %>%
  mutate(case_fatality_percent = `CASE-FATALITY`*100,
         undernourishment_x = if_else(undernourishment_percent=="<2.5", 2.5, as.numeric(undernourishment_percent)))

```

### Relatiosnhip between fatality rate and undernourishment rate by the country

```{r} 
# Ggplot to show relatiosnhip between fatality rate and undernourishment rate by the country


final_data %>%
  remove_missing() %>%
  drop_na() %>%
  ggplot(aes(x = undernourishment_x, y = case_fatality_percent, fill(Area)))+
  geom_point()+
  geom_jitter(height = 2, width = 2)+
  geom_smooth(method = lm)+
  scale_x_continuous(expand = c(0, 0)) + scale_y_continuous(expand = c(0, 0))+
  theme(axis.line = (element_line(colour = "black", size = 0.5, linetype = "solid")))+
  theme(axis.text.x = element_text(face="bold", color="black", size=10)) +
  theme(axis.text.y = element_text(face="bold", color="black", size=10))+
  labs(title= "Relationship between Undernourishment Rate and Fatality Rate" , x = "Undernourishment Rate", y = "Fatality Rate")



```

final_data %>%
  remove_missing() %>%
  drop_na() %>%
  ggplot(aes(x = case_fatality_percent))+
  geom_histogram()+
  labs(title= "Distribution of Fatality Rate" , x = "Fatality Rate", y = "Count")


